### ISSUE TITLE
RPCh organisation

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#1]
### Description

Tasks required to begin the RPCh team, non-software related.

### Relevant issues

- [x] create a new GitHub org @mjadach-iv 
  - move RPCh repository
  - move RPCh issues and epics
  - add members into the organization (Steve and Michal admins)
- [ ] document RPCh's processes @nionis 
  - [x] development
  - [ ] release
  - [x] wallets
  - [ ] evaluations
- [ ] onboard RPCh team
  - [x] messaging chat
  - [x] create messaging chat rooms
  - [x] create workspaces group
- [x] specify onboarding details with the existing HOPR team
- [x] creation of meetings
  - [x] epic priorities, sprint retrospective, sprint planning
  - [x] daily syncs
  - [x] HOPR education
  - [ ] Tech mingle call @mjadach-iv 
  - [ ] Steve <> RPCh team 1-1 @nionis 
- [ ] education
  - [ ] Ethereum basics
  - [ ] HOPR basics
  - [ ] RPCh processes once @nionis has committed them
  - [ ] RPCh _old_ code
  

### Definition of DONE

The RPCh team is ready to start working on the software side of things whilst the underlying organisational processes/tooling have already been set up and understood.
