### ISSUE TITLE
Martin's introduction to RPCh

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#108]
### Description

Martin's introduction to RPCh.

### Relevant issues

- [x] join the github organisation
- [x] join RPCh element groups
- [x] meet the RPCh team (via daily call)
- [x] read [processes](https://github.com/Rpc-h/.github/blob/main/processes/index.md)
- [x] checkout [monorepo](https://github.com/Rpc-h/rpch)
- [x] introduction to [monorepo](https://github.com/Rpc-h/rpch) (via Michal)

### Definition of DONE

Once Martin has been onboarded to RPCh.
