### ISSUE TITLE
review and improve infrastructure files

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#109]
### Description

Review and improve all RPCh's dockerfiles and docker-compose files.

### Relevant issues

- [x] https://github.com/Rpc-h/RPCh/issues/91
- [x] https://github.com/Rpc-h/RPCh/issues/90
- [ ] https://github.com/Rpc-h/RPCh/issues/79
- [ ] investigate which nodejs image to use in our Dockerfiles

### Definition of DONE

Once tasks are completed and code is committed to `main`.
