### ISSUE TITLE
implementation of discovery platform part 2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#114]
### Description

Implement remaining discovery platform features.

### Relevant issues

- [ ] indexer
- [ ] honesty score
- [x] add app level cache
- [x] move quota sum to be done on DB instead of app level
- [x] compress responses with gzip
- [x] add server timeout set to `30s`
- [ ] add concurrent testing
- [ ] add circuit breaker

### Definition of DONE

Features have been committed to main.
