### ISSUE TITLE
integration of RPC response validator

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#122]
### Description

Find an RPC response validator to integrate to RPCh.

Options:
 - Kevlar
 - Helios

### Relevant issues

- [ ] research on possible RPCh validators
  - [ ] check if Kevlar still does not work
    - [ ] check if we can use external provider
  - [ ] research helios
- [ ] draft a plan to integrate it in RPCh SDK
- [ ] integrate into RPCh SDK

### Definition of DONE

Once a validator is part of the RPCh ecossytem.
