### ISSUE TITLE
Select reliable nodes actively

### ISSUE THREAD

**Issue by ItsLuized** [Rpc-h/RPCh#126]
### Description

We should check the reliability score of nodes to make sure we are selecting the best nodes possible.
This should be achieved by actively checking, before or after a request, the reliability score and if it's bad, we should select a more reliable node.

### Relevant issues

- [x] Check before or after a request for the reliability score of the entry and exit node.
- [x] Select a different node if it's dishonest or it has a bad score.
- [x] All test pass

### Definition of DONE

We should have a PR with the implementation linked to this issue.
