### ISSUE TITLE
improvements and bug fixes basket

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#132]
### Description

Various small things that don't need their own `epic`.

### Basket

- [x] Rpc-h/RPCh#121 
- [x] Rpc-h/RPCh#123 
- [x] Rpc-h/RPCh#124 
- [x] https://github.com/Rpc-h/RPCh/issues/82
- [x] https://github.com/Rpc-h/RPCh/issues/110
- [x] https://github.com/Rpc-h/RPCh/issues/119
- [x] https://github.com/Rpc-h/RPCh/issues/117
- [x] https://github.com/Rpc-h/RPCh/issues/140
- [x] https://github.com/Rpc-h/RPCh/issues/155
- [x] https://github.com/Rpc-h/RPCh/issues/153
- [x] https://github.com/Rpc-h/RPCh/issues/152
- [x] https://github.com/Rpc-h/RPCh/pull/156
- [x] https://github.com/Rpc-h/RPCh/issues/158
- [x] https://github.com/Rpc-h/RPCh/issues/160
- [x] https://github.com/Rpc-h/RPCh/issues/166
- [x] https://github.com/Rpc-h/RPCh/issues/164
- [x] https://github.com/Rpc-h/RPCh/issues/175
- [x] https://github.com/Rpc-h/RPCh/issues/176
- [x] https://github.com/Rpc-h/RPCh/issues/178
- [x] https://github.com/Rpc-h/RPCh/issues/193
- [x] https://github.com/Rpc-h/RPCh/issues/192
- [x] https://github.com/Rpc-h/RPCh/issues/199
- [x] https://github.com/Rpc-h/RPCh/issues/195
- [x] https://github.com/Rpc-h/RPCh/issues/207
- [x] https://github.com/Rpc-h/RPCh/issues/217
- [x] https://github.com/Rpc-h/RPCh/issues/177
- [x] https://github.com/Rpc-h/RPCh/issues/220
- [x] https://github.com/Rpc-h/RPCh/issues/235
- [x] https://github.com/Rpc-h/RPCh/issues/229
- [x] https://github.com/Rpc-h/RPCh/issues/230
- [x] https://github.com/Rpc-h/RPCh/issues/243

## Optional
- [x] https://github.com/Rpc-h/RPCh/issues/214
- [x] https://github.com/Rpc-h/.github/issues/8
- [x] https://github.com/Rpc-h/RPCh/issues/202
- [x] Rpc-h/infrastructure#12

### Definition of DONE

Once all basked issues are completed.

**Comment by nionis** [comment]
Moving remaining issues to https://github.com/Rpc-h/RPCh/issues/247
