### ISSUE TITLE
RPCh hosting centralised services

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#133]
### Description

This `epic` encapsulates the work that needs to be done to host centralised services for both `staging` and `production`.
For RPCh centralised services (`apps/funding-service`, `apps/discovery-platform`) we will be hosting them in `GCP`.

### Relevant issues

- [x] setup configuration files for RPCh centralised services (https://github.com/Rpc-h/RPCh/issues/128)
- [x] complete staging setup for RPCh under domain (? rpch.tech)
- [x] complete production setup for RPCh under domain (?)

### Definition of DONE

Once RPCh centralised services are up and running.

**Comment by nionis** [comment]
Completed :)
