### ISSUE TITLE
RPCh v1.0.0-alpha infrastructure

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#142]
### Description

This `epic` encapsulates the work that needs to be done to host the RPCh alpha environment:
- For RPCh centralised services (`apps/funding-service`, `apps/discovery-platform`, `devkit/manager`) we will be hosting them in `GCP`
- For RPCh decentralised services (5x HOPRd + exit-nodes) we will be hosting them in `Hentzer` (for the time being we use `GCP`)

Services:
- `apps/funding-service`: accessible only by `apps/discovery-platform`, postgres DB
- `apps/discovery-platform`: publically accessible on domain: `https://alpha.discovery.rpch.tech/`, postgres DB
- `devkit/manager`: accessible only by the RPCh team (port forwarding)
- `decentralised services`: publically accessible, persist the volume

### Relevant issues

- [x] setup configuration files for RPCh centralised services (https://github.com/Rpc-h/RPCh/issues/128)
- [x] complete staging setup for RPCh under domain (rpch.tech)
- [x] implement `devkit/manager` @nionis 
- [x] chart for `devkit/manager` @sitilge 
- [x] create script that interacts with cluster and uses `devkit/manager` @nionis 
- [x] quick guide on updating the cluster / viewing logs / etc
- [x] test setup

### Definition of DONE

Once RPCh centralised services are up and running in alpha.

**Comment by sitilge** [comment]
Yes, I think the points, for the very, very first alpha is OK.

**Comment by nionis** [comment]
Alpha launched, creating a new issue for the HOPRd problems.
