### ISSUE TITLE
create all meetings for RPCh team

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#22]
### Description

Create all recurring calls for the RPCh team, also create calls for the onboarding week.

### Relevant issues

- [x] sprint planning calls: epic priorities, sprint retrospective, sprint planning
- [x] daily sync call
- [x] educational calls for the onboarding week
- [x] tech mingle call
- [x] Steve <> RPCh team 1-1

### Definition of DONE

All calls have been created and RPCh team is invited.

**Comment by nionis** [comment]
All done.
