### ISSUE TITLE
educational calls for RPCh team

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#23]
### Description

~Blocked by #22~

Ensure that the new RPCh team has been sufficiently educated on what ethereum, HOPR, and RPCh are.

#### @ItsLuized 

- [x] HOPR company: Code of Conduct, Policy, call with Vanessa
- [x] ethereum basics (ETH whitepaper): know what Ethereum is and understand at a high level understand _how it works_
- [x] HOPR basics: know what HOPR is and understand at a high level understand _how it works_
- [x] RPCh basics: know what RPCh is and understand at a high level understand _how is will be used_
- [x] read [old RPCh code](https://github.com/hoprnet/RPCh)

#### @diegoalzate 

- [x] HOPR company: Code of Conduct, Policy, call with Vanessa
- [x] ethereum basics (ETH whitepaper): know what Ethereum is and understand at a high level understand _how it works_
- [x] HOPR basics: know what HOPR is and understand at a high level understand _how it works_
- [x] RPCh basics: know what RPCh is and understand at a high level understand _how is will be used_
- [x] read [old RPCh code](https://github.com/hoprnet/RPCh)

#### @camilovegag 

- [x] HOPR company: Code of Conduct, Policy, call with Vanessa
- [x] ethereum basics (ETH whitepaper): know what Ethereum is and understand at a high level understand _how it works_
- [x] HOPR basics: know what HOPR is and understand at a high level understand _how it works_
- [x] RPCh basics: know what RPCh is and understand at a high level understand _how is will be used_
- [x] read [old RPCh code](https://github.com/hoprnet/RPCh)

### Definition of DONE

Once all new RPCh team members have crossed all educational materials.

**Comment by nionis** [comment]
Everyone had a first look at the above educational tasks, the rest will be learned through working on RPCh.
