### ISSUE TITLE
tangling issues

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#247]
### Description

Tangling issues which don't have their own `epic` yet.

- [x] https://github.com/Rpc-h/RPCh/issues/163
- [x] https://github.com/Rpc-h/RPCh/issues/173
- [ ] https://github.com/Rpc-h/RPCh/issues/210
- [ ] https://github.com/Rpc-h/RPCh/issues/212
- [x] https://github.com/Rpc-h/infrastructure/issues/11
- [x] https://github.com/Rpc-h/RPCh/issues/228
- [x] https://github.com/Rpc-h/RPCh/issues/248
- [x] GPC cluster -> dedicated GCP servers
- [x] https://github.com/Rpc-h/RPCh/issues/285
- [x] https://github.com/Rpc-h/RPCh/issues/301
- [x] https://github.com/Rpc-h/RPCh/issues/189
- [x] https://github.com/Rpc-h/RPCh/issues/213
- [ ] https://github.com/Rpc-h/.github/issues/7
- [ ] https://github.com/Rpc-h/RPCh/issues/239
- [x] https://github.com/Rpc-h/helm-charts/issues/5
- [x] https://github.com/Rpc-h/RPCh/issues/326
- [x] https://github.com/Rpc-h/RPCh/issues/323
- [x] https://github.com/Rpc-h/RPCh/issues/322
- [x] https://github.com/Rpc-h/RPCh/issues/320
- [x] https://github.com/Rpc-h/applications/issues/7
- [x] https://github.com/Rpc-h/RPCh/issues/341
- [x] https://github.com/Rpc-h/applications-platform/issues/32
- [x] https://github.com/Rpc-h/RPCh/issues/342
- [ ] https://github.com/Rpc-h/RPCh/issues/347
- [x] https://github.com/hoprnet/hopr-devops/issues/128
- [ ] https://github.com/Rpc-h/RPCh/issues/356
- [x] https://github.com/Rpc-h/applications/issues/11
- [x] #365
- [ ] back-merge https://github.com/Rpc-h/RPCh/commits/running-staging-release
- [ ] https://github.com/Rpc-h/RPCh/issues/369
- [x] https://github.com/Rpc-h/RPCh/issues/373
- [x] https://github.com/Rpc-h/RPCh/pull/386
- [ ] https://github.com/Rpc-h/crypto/issues/11
- [x] https://github.com/Rpc-h/RPCh/issues/388
- [ ] https://github.com/Rpc-h/RPCh/issues/377
- [ ] request tracing = traces the request through rpc-server, entry node, exit node
- [ ] DB metrics = lacking in our grafana
- [ ] add RPCh usage metrics by looking into quota used in DP

### Definition of DONE

Once all basked issues are completed.
