### ISSUE TITLE
[DRAFT] RPCh v1.0.0-beta

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#264]
The `beta` release of RPCh.

Issues:

- [x] #266 
- [ ] #268 
- [ ] https://github.com/Rpc-h/applications/issues/2
- [ ] #269 
- [ ] #270 
- [x] #114 
- [ ] https://github.com/Rpc-h/RPCh/issues/271
- [x] #273 
- [x] #272 
- [ ] #122 
- [ ] #223 
- [ ] https://github.com/Rpc-h/RPCh/issues/276 
- [ ] #284 
- [ ] https://github.com/Rpc-h/RPCh/issues/247
- [ ] monitor
- [ ] testing session

Maybe:

- [x] #274 
- [ ] #135 
- [ ] #136

**Comment by esterlus** [comment]
obsolete
