### ISSUE TITLE
improve codebase hygiene n1

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#266]
### Description

Improve general code quality in the codebase.
Contains a mix of issues/improvements to do.

##### General

- [x] ~~`./turbo.json`: lots of duplication in `#build` sections - try to reduce it~~
- [x] lint: trigger on unused imports
- [x] https://github.com/Rpc-h/RPCh/issues/278
- [x] `./configs/*` not all index.js contain typescript definitions
- [x] Use of constant files in all `./apps/*`

#### rpc-server

- [x] #287

##### manager

- [x] validate query inputs
- [x] reduce “as any” & increase typing
- [x] move contract ABI functions to a separate library

##### ethers

- [x] #291
- [x] #299
- [x] #290

##### SDK

- [x] fetch exit node: no status code validation
- [x] always logs `selected new entry node`
- [x] document `0.7` variable
- [x] more consistent naming in variables
- [x] add comments to tests onmessage
- [x] remove isdeadlock from create request
- [x] remove “got new entry node” log
- [x] add comment to freshnodethreshold
- [x] reliability score redundant constructor
- [x] simplify add metric

##### apps/fs & apps/dp

- [x] unnecessary folders
- [x] duplicate replacer
- [x] reduce use of `?.`
- [x] del architecture image
- [x] reduce return type cases
- [x] more constants
- [x] normalize types RegisteredNode, CreateRegisteredNode, QueryRegisteredNode
- [x] refactor funding service middleware

##### exit node

- [x] #313

##### common

- [ ] Type return createLogger
- [x] Internal section in common similar to fixtures
- [ ] Maintain WS connection
- [x] `./cache.ts` needs comments

### Definition of DONE

Once the following tasks have been completed or individually moved into separate epics.

**Comment by nionis** [comment]
Moved crypto items to #328

**Comment by nionis** [comment]
Closing and moving the remaining item into a tangling issue.
