### ISSUE TITLE
improve rewarding system

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#268]
### Description

Blocked by #270 

Improve how we hand out rewards to node runners.

Assumptions: 
- we have added the capability based API
- there is a 1% chance of redeeming a ticket
- for each request the SDK does, a client spends 1 quota
- collusion is not taken into account
- 1 quota = 1 message send to a HOPRd node
- ticket win rate: 1%
- client: our client, ex: blockwallet
- user: the SDK user

We will start to reward nodes depending on how many tickets have been redeemed and how much quota is being used. So for example if an entry node redeems 2 tickets and there is a 1% win rate we will assume he used only 200 quota out of 500 quota. This means we will refund the client 's unused quota. We auto reduce the client’s quota whenever we ask for quota from capability based api but we do not want to charge unused quota.

However this does not reward exit nodes. Since exit nodes are chosen randomly it is very hard to know what client sent a message and who to charge for that request. An exit node sends the request to the provider and back to the entry node so it is a 2 step process that is hard to reward and track without going for a non private approach. We measure the hopr spent on chain of the exit node and we take the quota that was used from the exit node and that way we can calculate how much approx was used.

- win_rate = 1%
- redeemed_ticket = tickets redeemed on-chain
- actual_quota = redeemed_tickets / win_rate (how much quota was used)
- assigned_quota = how much quota was assigned by the DP

Calculating client's quota charge-back:

- assigned_quota - actual_quota = charge-back

Calculating entry node reward:

- actual_quota + 10% -> reward in HOPR

Calculating exit node reward:

- actual_quota - assigned_quota = quota_reward + 10% -> reward in HOPR

### Relevant issues

- [ ] separate `request/entry-node` with rewards
- [ ] using capability based API, keep track of quota used by the SDK
- [ ] airdrop rewards every 1 hour
- [ ] keep track of how many `calls` were done per token via capability based API

### Definition of DONE

TBD

**Comment by diegoalzate** [comment]
![image](https://user-images.githubusercontent.com/22416585/226944465-9248800a-e442-4669-9ce1-281aaa73378c.png)

**Comment by mjadach-iv** [comment]
Pushing after ETH Privacy

**Comment by esterlus** [comment]
reopen when applicable
