### ISSUE TITLE
implement MEV blocker

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#269]
### MEV protection in SDK

The SDK should provide MEV protection.
This integration should be configurable and come with sane defaults.
It should also be overridable on a per request base.

This needs some adjustments to the SDK API.

One possible integration path could look like this:

The SDK `constructor` initializes a default MEV protection endpoint (propellorhead endpoint).
This can be overridden by an constructor parameter to some other endpoint.

The SDK `send` function takes the usual JSON payload (e.g. `{"jsonrpc":"2.0","id":203177,"method":"eth_getBlockByNumber","params":["latest",false]}`).
The second parameter allows for additional configuration of the request, e.g.: `{enableMEV?: boolean, overrideMEVprotectionEndoint?: string}?`.
With this information the function can calculate if MEV protection should be enabled for `method` and `params` and what rpc provider to use (MEVprodiver | givenMEVprovider | defaultProvider).

### Definition of DONE

- [ ] implement MEV protection endpoint selection algorithm, depending on JSON RPC payload
- [ ] integrate with RPCh SDK with default parameters and optional overridable
- [ ] track client (wallet) usages of MEV protection endpoints depending on successful responses

**Comment by SCBuergel** [comment]
Let's replace FB Protect by https://mevblocker.io/

**Comment by nionis** [comment]
@esterlus whats the benefit of the sibling function over using `sendRequest`?

**Comment by esterlus** [comment]
I don't want to change the API of `sendRequest` yet. Let's do that ourselves once we verified everything works fine.
