### ISSUE TITLE
implementation of RPCh exit node 1/2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#27]
### Description

Implement part 1/2 of RPCh exit node, no encryption/decryption capabilities.

### Relevant issues

- [x] create `exit node` package in this repository
- [x] retrofit components from [RPCh prototype](https://github.com/hoprnet/RPCh) into this new library
- [ ] create docker-compose file to run alongside HOPRd
- [x] add testing, coverage >90%
- [x] add documentation

### Definition of DONE

Once we have a docker-compose file that allows RPCh exit node to run alongside HOPRd.
