### ISSUE TITLE
implement capability based API

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#270]
### Description

Implement capability-based API into the SDK and discovery platform.

blocked by  https://github.com/hoprnet/hoprnet/issues/4755
blocked by https://github.com/hoprnet/hoprnet/issues/4765

### Relevant issues

See `capability-based API` docs in HOPR's swagger `tokens` section.

##### Discovery Platform

- [x] discovery platform should request a token for itself with capabilities: `tokensCreate`, `tokensGetToken`, `tokensDelete`
- [x] discovery platform should request a token for the SDK with capabilities: `messagesWebsocket`, `messagesSendMessage`, `tokensGetToken`
- [x] send the SDK token to the SDK

##### SDK

- [x] receive token from DP
- [x] keep track of `calls` made to the token
- [x] request for new token once calls run out

### Definition of DONE

Capability based API is used throughout RPCh stack.

**Comment by nionis** [comment]
if this late in the week we cannot merge it in
