### ISSUE TITLE
improve DP stability

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#272]
### Description

Improve the stability of the discovery platform.

### Relevant issues

- [x] investigate most performance consuming points of DP
- [x] investigate what it takes to be able to have multiple replicas (redis?)
- [x] implement devops changes for allowing replicas
- [x] https://github.com/Rpc-h/RPCh/issues/306

### Definition of DONE

Once we can run multiple DP in parallel.

**Comment by diegoalzate** [comment]
# Performance observations
- Staging environment can handle up to 2000 connections, while sandbox local can handle only 250 connections.
- **`/api/v1/node`** route is performing well, with an average response time of under 1 second (965.76 ms) and handling up to 438 requests per second with 250 connections on the local sandbox environment. Staging environment can handle up to 1500 connections and process up to 2749 requests per second with an average response time of 1104.8 ms.
- **`/api/v1/request/trial`** route is also performing well with an average response time of around 1 second (1004.32 ms) and handling up to 420 requests per second with 250 connections on the local sandbox environment.
- **`/api/v1/request/entry-node`** route is performing moderately well with an average response time of around 1.5 seconds (1475.18 ms) and handling up to 279 requests per second with 250 connections on the local sandbox environment.
- **`/api/v1/client/quota`** route has the highest average response time of all routes, at around 2 seconds (2045.7 ms) on the local sandbox environment, and can only handle up to 60 requests per second with 250 connections.

# Bottlenecks
- looks like checking checkCommitmentForFreshNodes


![Image](https://user-images.githubusercontent.com/22416585/230206536-07bf5535-47b4-4d67-9e9b-b638b3a616fe.png)
