### ISSUE TITLE
implement metrics part 1/2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#281]
### Description

Gather metrics for DP, FS, and exit-nodes.

### Relevant issues

- [x] implement metrics for the discovery platform (pull method)
- [x] implement metrics for the funding service (pull method)
- [ ] implement metrics for exit-node (enabled via ENV, should be toggled on in our docker-compose files)
- [x] implement Prometheus cluster for `our` metrics

### Definition of DONE

Our grafana dashboard is populated with our metrics.
