### ISSUE TITLE
RPCh v1.0.0

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#3]
### Description

The roadmap to RPCh v1.0.0.

#### organisational
- [x] #1
- [x] #11

##### specifications
- [ ] #6 
- [ ] #7 
- [ ] #9 
- [ ] #8 
- [ ] Spec of funding service
- [x] #10 
- [x] #12 

##### implementations
- [x] #14
- [x] #15
- [x] #16
- [ ] implement discovery platform
- [ ] implement funding service
- [ ] implement ethers RPCh adaptor

##### wrapping up
- [ ] integrate with RPC providers
- [ ] release v1.0.0

### Possibly blocked by

- core: token and quota-based limited access API, token based access to WS streams
- core: API to create such token ^
- core: spec an encryption mechanism for entry and exit nodes
- core: fix multi-hop rapid message sending
- core: ensure promiscuous strategy is working
- core: access to NR or no NR
- core: packet cost per HOPR

### Post v1.0.0

- [ ] #4 
- [x] Archive prototype repository https://github.com/hoprnet/RPCh

### Definition of DONE

We have an official v1.0.0 release accompanied by the relevant SDK/tooling, additionally, we have a working and healthy RPCh network which wallets can use.
