### ISSUE TITLE
Code Hygiene - Manager

### ISSUE THREAD

**Issue by ItsLuized** [Rpc-h/RPCh#304]
Related to #266 

### Description

This issue aims to improve the code quality of the `manager` package of `devkit`. This will help the future developments on this packages by having clean, readable and maintainable code.

The proposed solution involves the reduction of "as any" and increasing typing, validating query inputs, moving contract ABI functions to a separate library and removing ESLint since it's not used.

### TODOs

- [x] validate query inputs
- [x] reduce “as any” & increase typing
- [x] move contract ABI functions to a separate library => Including FS
