### ISSUE TITLE
implementation of RPCh SDK 1/3

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#32]
### Description

Implement part 1/3 of RPCh SDK.

### Relevant issues

- [x] retrofit hoprd component from [RPCh prototype](https://github.com/hoprnet/RPCh)
- [x] retrofit manager component to request-cache component from [RPCh prototype](https://github.com/hoprnet/RPCh)
- [ ] add testing, coverage >90%
- [ ] add documentation

### Definition of DONE

Once we have a working RPCh SDK library with limited capabilities.
