### ISSUE TITLE
implementation of RPCh SDK 3/3

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#34]
### Description

Implement part 3/3 of RPCh SDK.

### Relevant issues

- [x] implement reliability score
- [x] implement interactions with the discovery platform
- [ ] ~implement kevlar~
- [x] add testing, coverage >90%
- [x] add documentation

### Definition of DONE

Once we have a working RPCh SDK library with limited capabilities.

**Comment by SCBuergel** [comment]
It seems that Kevlar is not sufficiently reliable (services unavailable) to use in production settings right now. Since we cannot expect this to majorly change by end of February so [we will explore Helios as an alternative](https://github.com/Rpc-h/RPCh/issues/122)

**Comment by nionis** [comment]
Removing Kevlar/Helios from this epic and moving them into separate epics

**Comment by nionis** [comment]
Closed by #80 and #115
