### ISSUE TITLE
Use the compression functions in RPCh (2/2)

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#350]
### Description

Use the compression functions in RPCh

### Definition of DONE

- [ ] Use the compression functions in RPCh
- [ ] test with sandbox
- [ ] Update all Unit tests
