### ISSUE TITLE
implementation of RPCh ethers adaptor

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#37]
### Description

Blocked by #36 and #32 

Implementation of RPCh ethers adaptor v1.0.0

### Relevant issues

- [x] create an adaptor which speaks ethers
- [x] implement RPCh SDK in the adaptor
- [x] make SDK available to the codebase once adaptor is imported
- [x] add testing, coverage >90%
- [x] add documentation

### Definition of DONE

Once RPCh ethers adaptor is implemented with sufficient testing and documentation.
