### ISSUE TITLE
RPCh v0.2.0

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#370]
### Description

Releasing compression & stability improvements.

### Relevant issues

- [x] we check how the GCP nodes behaved overnight
    - if good (as good as Hentzer): we keep using them, remove Hentzer, and increase the number of nodes
    - if bad: we spend sometime to see why (maybe issue is not related to HOPRd) - if unfixable by 12:00 PM, we revert to Hentzer and manually add more nodes
- [x] create more Hentzer nodes
- [x] create script to update Hentzer nodes
- [x] final tests on compression
- [x] back-marge last RPCh release to master
- [x] release new libraries and update downstream apps and services
    - [x] BW, Frame @diegoalzate 
    - [x] Enrkypt @ItsLuized 
    - [x] sandboxes @nionis 
    - [x] Hentzer and GCP exit-nodes @nionis 
    - [x] update regexp given to Lukas @diegoalzate 

### Definition of DONE

Release v0.2.0 out and everything is ready for IST hackathon.

**Comment by nionis** [comment]
All tasks complete.
