### ISSUE TITLE
implement availability monitor

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#391]
### Description

HOPRd nodes and RPCh exit nodes are registered in the discovery platform.
While the discovery platform serves these nodes to users, we need to ensure that said nodes are at the time of serving fully operational and in a good state.
Additionally, we need to ensure that _nodes_ provide the services they claim to provide.

Availability Monitor (AM) is a new [app](https://github.com/Rpc-h/RPCh/tree/main/apps) in the RPCh ecosystem. Its sole purpose is to gather availability datapoints of a given list of HOPRd nodes and RPCh exit nodes.

Objectives:

- monitor all registered nodes
- provide current and historical data on the nodes
- scalable and independent of DP

Flow:

- node is registered in DP (registered as _unavailable_)
- DP notifies AP (Availability Monitor) of the new node
- AP will now store availability datapoints of the given node every (?) minutes
  - HOPRd: network health check
  - HOPRd: number of outgoing + funded channels
  - HOPRd: accessible API endpoint
  - HOPRd: SSL protected or not
  - HOPRd: via making a Request, test message delivery
  - HOPRd: number of connected nodes
  - RPCh exit node: via making a Request, test exit-node support
- AP can update DP node list once a given node is unavailable
- AP can update DP node list once a given node is available
- bonus: all datapoints available in grafana dashboard
- bonus: DP may ask AM for information on a new node

### Relevant issues

- [x] create starter for availability-monitor app
- [x] implement read & write to DB
- [x] implement various checks for HOPRd nodes
- [x] make part of our cluster (https://github.com/Rpc-h/applications/issues/36)

### Definition of DONE

Once availability-monitor is running in our staging environment and the discovery-platform is using it. All nodes given by the discovery-platform should have been checked by availability-monitor.

**Comment by ausias-armesto** [comment]
As mentioned in the meeting, you might consider useful for the future to add additional business metrics from the hoprd node like:
- node uptime
- nº node restarts
- nº node relayed nodes
- is node a PRN
- rate of messages sent and received
- avg response time for messages and pings
- ...

So the discovery platform can have more attributes to determine the load balancing.

**Comment by nionis** [comment]
Moving remaining work to https://github.com/Rpc-h/RPCh/issues/410, thanks all!

**Comment by nionis** [comment]
Reopening until it's used by DP

**Comment by nionis** [comment]
Done
