### ISSUE TITLE
various stability improvements

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#401]
### Description

A collection of stability improvements planned for v0.3.0

### Relevant issues

- [x] https://github.com/Rpc-h/RPCh/issues/399
- [ ] https://github.com/Rpc-h/RPCh/issues/400
- [x] https://github.com/Rpc-h/RPCh/issues/387
- [ ] https://github.com/Rpc-h/RPCh/issues/390
- [x] https://github.com/Rpc-h/latency-monitor/issues/9
- [ ] https://github.com/Rpc-h/RPCh/issues/325
- [x] https://github.com/Rpc-h/latency-monitor/issues/10
- [x] no re-select after deadlock (fixed via https://github.com/Rpc-h/RPCh/pull/408)
- [x] add back ascii fix https://github.com/Rpc-h/RPCh/pull/413
- [x] exit node selection can pick one of the entry nodes
- [ ] https://github.com/Rpc-h/RPCh/issues/421

### Definition of DONE

Once all issues have been merged and available in v0.3.0.
