### ISSUE TITLE
Payment System: Client usage tracking

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#445]
### Description

We need to be able to track a particular's client (identified by client id) usage of RPCh, specifically # of PRC calls made. This number should be queryable over a custom period of time.

We need a dashboard (in-house) to view custom queries on that data.

A client must be associated with a service plan. Service plans can be re-usable between clients.

Part of #397 

### Definition of DONE

- [ ] dashboard is allowing custom querying
- [ ] customers can be identified by client id
- [ ] customers are associated with service plans
- [ ] service plans can be administered in the dashboard
- [ ] customer/service plan relationship can be administered in the dashboard

**Comment by nionis** [comment]
After syncing with Ronny, on the initial version of this (until we introduce service plans), I will be working on the first version without the inclusion of the service plans.

**Comment by nionis** [comment]
[link](https://github.com/Rpc-h/dashboard-rpch-net) to the repository

**Comment by esterlus** [comment]
Except for the admin part this is integrated.
Admin part will get a separate ticket.
