### ISSUE TITLE
Payment System: Integration of payment provider

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#446]
### Description

We need an integration which allows a new user (client) to pay for a service plan with USD (fiat) and receive the respective allocation of RPC calls in RPCh. Moreover, RPCh should receive xHOPR (Gnosis Chain) tokens. Ideally the integration takes care of all intermediate steps.

We must have a non-public page which new clients can use to make payments and be assigned to a particular service plan.

The development of public payment pages will be handled in a separate epic.

Payment data is associated to clients in the RPCh administration system and viewable through the RPCh dashboard.

Requires #445 
Part of #397 

### References

- https://www.moonpay.com/en-gb
- https://stripe.com/docs/crypto/overview
- https://ramp.network

### Definition of DONE

- [ ] non-public payment page is online and working
- [ ] payment integration works, xHOPR can be received
- [ ] new clients are created in RPCh with the respective metadata about their payments
