### ISSUE TITLE
post-spec completion

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#50]
### Description

Blocked by https://github.com/Rpc-h/RPCh/issues/67

What happens after specs have been completed.

### Relevant issues

- [x] modify 2 pager @nionis 
- [x] discuss version #45 with team
- [x] update STARMAP @nionis 

### Definition of DONE

All tasks above are completed
