### ISSUE TITLE
RPCh commons additions

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#52]
### Description

According to the updated spec, we need to make small modifications on the placement of various functions.

### Relevant issues

- [x] remove `hoprd.ts` and `hoprd.spec.ts` from `SDK` and `exit-node`
- [x] add `hoprd.ts` to `commons`
- [x] import `hoprd.ts` functionality to `SDK` and `exit-node`
- [x] remove `request-tracker.ts` and `request-tracker.spec.ts` from `exit-node`

### Definition of DONE

Above tasks are completed and we are in line with the spec for part 1.
