### ISSUE TITLE
optimize production builds and repo

### ISSUE THREAD

**Issue by esterlus** [Rpc-h/RPCh#521]
- [ ] cleanup monorepo
- [ ] check if we build correct production builds and adhere to best practices there
- [ ] understand DEBUG npm package and better and see how we can set correct log levels
- [ ] enhance github workflows to better fit our needs
