### ISSUE TITLE
Quota handling

### ISSUE THREAD

**Issue by esterlus** [Rpc-h/RPCh#524]
Imlement correct quota handling

- [ ] better error messages on out of quota errors, related: #513 
- [ ] enforce quota usage on exit-node
- [ ] monthly quota aggregation in DP needs to handle month wrapping
