### ISSUE TITLE
b2b admin platform for self-service

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#545]
Customers should be able to administer their account and used feature-set themselves via a dedicated platform.

### Definition of Done

- [ ] platform is deployed in production
- [ ] platform is accessible via a public URL
- [ ] customers can sign in
- [ ] customers can manager their account on the platform
