### ISSUE TITLE
Extendable RPCh SDK

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#548]
Extendable RPCh SDK to enable 3rd-party contributions to include additional value-added services 

### Definition of Done

- [ ] SDK has reached v1.0.0
- [ ] SDK documentation is available to developers
- [ ] Extension points are documented and tested
- [ ] Examples for extensions are given
