### ISSUE TITLE
Automated load testing and production capacity calculation

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#551]
We need a way to project the load which the production network can handle. This information is the base for onboarding new wallets as it determines whether we need to scale up the production network.

### Definition of Done

- [ ] k6 load testing scenario which mimics realistic RPC calls and can be run locally
- [ ] k6 load testing scenario can be started via Github Actions button
- [ ] k6 load testing scenario is run nightly on GHA automatically
- [ ] results are accessible in Grafana
- [ ] separate dashboard which projects the possible load on our production network
