### ISSUE TITLE
implement coverage into our toolchain

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#58]
### Is your feature related to a problem?

No

### Describe the feature you'd like

Implement coverage reports into our toolchain.

- [x] a command to get a coverage report via the CLI
- [ ] with every PR, get a coverage report and a diff
- [ ] add automated `dependency checks`

**Comment by nionis** [comment]
maybe useful:

- `jest --coverage`
- https://github.com/marketplace/actions/code-coverage-report
