### ISSUE TITLE
Complete and document RPCh 1-hop funds flow

### ISSUE THREAD

**Issue by tolbrino** [Rpc-h/RPCh#623]
### Description

Ensure all manual and automatic processes related to keeping RPCh 1-hop running are documented and implemented. 

### Definition of DONE

- [ ] RPCh uses promisucous strategy configured to use peers with v2.1.0 and above
- [ ] Funds (xdai, wxhopr) in all safes used by RPCh and the main RPCh funding account are monitored
- [ ] Workflow for internal monthly accounting in the place and defined
- [ ] It is ensured that RPCh infra will not run out of funds without the team noticing
