### ISSUE TITLE
specs for RPCh v1.0.0 1/2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#67]
### Description

Specs for RPCh v1.0.0 which technically describe roughly how pieces fit together.
Important for our Starmap.

### Relevant issues

- [x] https://github.com/Rpc-h/RPCh/issues/18
- [x] https://github.com/Rpc-h/RPCh/issues/25
- [x] https://github.com/Rpc-h/RPCh/issues/30
- [x] https://github.com/Rpc-h/RPCh/issues/36
- [x] https://github.com/Rpc-h/RPCh/issues/39
- [x] https://github.com/Rpc-h/RPCh/issues/43

### Definition of DONE

When RPCh v1.0.0 specs can be used to update the Starmap.

**Comment by nionis** [comment]
Sufficiently completed specs to create our roadmap.
