### ISSUE TITLE
improve logging & metrics

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#76]
### Description

As we are developing RPCh, it's critical that we have a consistent and flexible logging system.
Currently, we rely on `common.utils.createLogger` which aims to provide three levels of logging.

1. `.log` is used for important logical milestones that make sense to log
2. `.logVerbose` verbose logging
3. `.logError` logging of errors

Additionally, it is expected that the developer which uses `createLogger` also uses the right paradigm, for example:
`createLogger(["funding-service", "access-token", "service"])` which would result in a log ID of `funding-service:access-token:service <some error>`.

Most importantly, the `createLogger` function does not provide the functionality for allowing us to utilize metrics, as it requires the metric analyzing system to use tools such as `regexp` to match with various logs and thus create metrics.

In this `epic` we aim on achieving the following:

1. adjust `createLogger` to require the developer to indicate the package in which it's used, example: `createLogger("funding-service" ..`
2. as the last argument of the log, allow the pass of a generic object which can take all sorts of variables in, this should be typed correctly via typescript

Example interface:

```typescript
type InterestingThings = Partial<{
  peerId: string,
  [key: any]: any
}>
type CreateLogger = (app: string, path: string[]) => (...args: any, forMetrics: InterestingThings) => { ... }
```

### Relevant issues

- [x] sync with RPCh on the proposal
- [x] sync with devops team on whether this metric object is useful at all
- [x] implement CreateLoggerFactory
- [x] update RPCh commons
- [x] update RPCh sdk
- [x] update RPCh ethers
- [x] update RPCh exit-node
- [x] update RPCh funding-service

### Definition of DONE

Once we have implemented a consistent logging system throughout the codebase which can be easily utilized by a metrics software.
