### ISSUE TITLE
implement release workflow

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#77]
### Description

Implement a release workflow that will publish our public packages.

- `npm publish` everything under `packages/**`
- publish docker images everything under `apps/**`

### Relevant issues

- [x] update release process
- [x] document versioning scheme
- [x] implement release workflow for NPM packages
- [x] implement release workflow for docker images

### Definition of DONE

Once we can make releases for all our packages and images.

**Comment by nionis** [comment]
I will close it and create a new epic with some improvements that need to be done
